### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by mirohu** [UBC-MDS/DSCI_532_Group213_death_by_risk_factors#17]
I was wondering if we should make the motivation part into different paragraphs? Feel like the current paragraph is a bit long.

**Comment by fsywang** [comment]
I have separated the paragraph and did some editing.

**Comment by fsywang** [comment]
The latex was not shown correctly in the github md file

**Comment by eyrakas** [comment]
Agree on splitting it to avoid it being lengthy.
