### ISSUE TITLE
Team Contract - Revised

### ISSUE THREAD

**Issue by eyrakas** [UBC-MDS/DSCI_532_Group213_death_by_risk_factors#23]
I have made a slight revision on the `Team Contract`, what do you think? do we need add/remove some points?

# Team Contract:

1. Time management - try finishing more than 3 hours before the deadline so it won’t be too rushed.
2. Respect each other and their work.
3. Group meetings to be held on Wednesdays during lab & Thursday after lab hours.
4. Active discussions through Github issues.
5. No communication hours between 10 pm to 6 am except for urgent matters.
6. Be reachable - try to response within 2 hrs during the day time
7. Communication is the key. If anyone feels unfair or not comfortable by any group decision, please always say it and let others know!

**Comment by mirohu** [comment]
Looks good to me. Thanks Sakariya!

**Comment by fsywang** [comment]
Looks good to me as well!
