### ISSUE TITLE
Links on the github.ubc.ca README

### ISSUE THREAD

**Issue by mirohu** [UBC-MDS/DSCI_532_Group213_death_by_risk_factors#24]
Hi! I was wondering if the 98beb7 would be our last version for the milestone? If so, I have created the links that you can put on our github.ubc.ca repo as follow:

[DSCI_532_Group213_death_by_risk_factors_commit_98beb7](https://github.com/UBC-MDS/DSCI_532_Group213_death_by_risk_factors/tree/98beb746417a7bf13160a9995222abad0b275a90)

[Group213_code_of_conduct](https://github.com/UBC-MDS/DSCI_532_Group213_death_by_risk_factors/blob/98beb746417a7bf13160a9995222abad0b275a90/CODE%20OF%20CONDUCT.md)

[Group213_proposal](https://github.com/UBC-MDS/DSCI_532_Group213_death_by_risk_factors/blob/98beb746417a7bf13160a9995222abad0b275a90/proposal.md)

[Group213_README](https://github.com/UBC-MDS/DSCI_532_Group213_death_by_risk_factors/blob/98beb746417a7bf13160a9995222abad0b275a90/README.md)

[Group213_team-work-contract](LINK NEEDS TO BE ADDED)

All the links are based on the latest version. Hope this can save you some work!

**Comment by mirohu** [comment]
[DSCI_532_Group213_death_by_risk_factors_commit_
712cd15](https://github.com/UBC-MDS/DSCI_532_Group213_death_by_risk_factors/tree/712cd156dfe6c0d7979f81114ce320f2db8ac51b)

[Group213_code_of_conduct](https://github.com/UBC-MDS/DSCI_532_Group213_death_by_risk_factors/blob/712cd156dfe6c0d7979f81114ce320f2db8ac51b/CODE%20OF%20CONDUCT.md)

[Group213_proposal](https://github.com/UBC-MDS/DSCI_532_Group213_death_by_risk_factors/blob/712cd156dfe6c0d7979f81114ce320f2db8ac51b/proposal.md)

[Group213_README](https://github.com/UBC-MDS/DSCI_532_Group213_death_by_risk_factors/blob/712cd156dfe6c0d7979f81114ce320f2db8ac51b/README.md)

[Group213_team-work-contract](NEED TO BE ADDED)

Updated to the latest version!

**Comment by fsywang** [comment]
Thanks Miro!

**Comment by eyrakas** [comment]
I just did some final proofreading and corrections on spelling and grammar. Reworded some areas in 2 of the Research Questions as well. You may have a look at it, everything else should be good to go.

**Comment by mirohu** [comment]
It looks great. Will update the link too.

**Comment by mirohu** [comment]
[DSCI_532_Group213_death_by_risk_factors_commit_
4c449ac](https://github.com/UBC-MDS/DSCI_532_Group213_death_by_risk_factors/tree/4c449acbfa4a897c376ca465fbf4f42287c6da5c)

[Group213_code_of_conduct](https://github.com/UBC-MDS/DSCI_532_Group213_death_by_risk_factors/blob/4c449acbfa4a897c376ca465fbf4f42287c6da5c/CODE%20OF%20CONDUCT.md)

[Group213_proposal](https://github.com/UBC-MDS/DSCI_532_Group213_death_by_risk_factors/blob/4c449acbfa4a897c376ca465fbf4f42287c6da5c/proposal.md)

[Group213_README](https://github.com/UBC-MDS/DSCI_532_Group213_death_by_risk_factors/blob/4c449acbfa4a897c376ca465fbf4f42287c6da5c/README.md)

[Group213_team-work-contract](NEED TO BE FILLED)

Updated final links!

**Comment by eyrakas** [comment]
Thanks Miro.
