### ISSUE TITLE
Reflection

### ISSUE THREAD

**Issue by eyrakas** [UBC-MDS/DSCI_532_Group213_death_by_risk_factors#38]
### Reflection

This application visualizes the global risk factors that contribute to human death and has well-designed features that provide answers to the research questions outlined in milestone 1 of this project. The app does so well in showing the top risk factors that contribute to global death and those that contribute to the least deaths. It also interactively shows in a choropleth in a geographic distribution on the percentage of death caused by each risk factor in every country in the world. Moreover, the app is so interactive that it allows the users to easily visualize the global death trends for various risk factors from 1990 up to 2017 using interactive features such as dropdown menus, radio buttons, etc.

On the other hand, since the development team was limited on time, this app has several limitations. Manipulating the dash font type and colours were difficult, this was indicated in-dash Plotly platform that such feature is under development. Another limitation is that while the dropdown menu for our map function works perfectly and has a default value set, it may sometimes render unexpectedly if the user hits to cancel option in the menu.

As such, several future improvements could be made which includes the following. The bar graph that shows `Overview` of the risk factors can have an additional range slider to allow users to choose the range of years they would like to see the overview of deaths caused by the various risk factors. Furthermore, the geo map that shows the `World Spread` of risk factors could have an additional feature such as generating a summary graph after the user highlights a group of countries. This would allow comparison among countries of interest.
Another improvement is the need to have an additional slider that allows users to choose the range of years for the `Trend` chart. This would enable users to choose any range of years while selecting the risk factor of their choice from the radio buttons which is currently implemented.

While there was no feedback obtained from TAs on our milestone1, we have completed the implementation and deployment of the dashboard application in a manner that fully reflects the functionalities promised in our research questions.

**Comment by mirohu** [comment]
This reflection covered all the points that I could think of. Perfect 💯

**Comment by fsywang** [comment]
I fixed the cancel option for the dropdown menu. We can delete this part:)
