### ISSUE TITLE
Dashboard feedback

### ISSUE THREAD

**Issue by aleurcelay** [UBC-MDS/DSCI_532_Group213_death_by_risk_factors#41]
Hi @eyrakas, @mirohu & @fsywang,
Your proposal looks very good and your topic is very relevant! 

Some comments that you might want to consider for milestone 2 regarding your sketch: 
- You could add a couple of sentences with information about your dashboard in the menu panel, including your data source
- Specify that the data displayed for the first two toggle buttons is for 2017. If you have time, consider adding widget to change the year of data
- Are the top 5 factors the same across all years of data?
- Consider making the plots 1 & 3 interactive as well

Also, remember there should be an equitable amount of contributions, each of you should have at least about 10 commits.

I hope this is helpful! Will add some more feedback on the overall assignment later.

**Comment by mirohu** [comment]
Thanks @aleurcelay !  We will try to cover them all.

**Comment by aleurcelay** [comment]
Hi @eyrakas, @mirohu & @fsywang,
As promised here's the rest of the feedback for milestone 1:

- Your code of conduct is good, however your team contract is too general. I would recommend going forward, clearly divide tasks, communicate your availability, and setting an earlier internal deadline to review your work together before submitting
-  Remember that your links have to be to specific commits
- Your proposal is clear and explains well the data used and the purpose of your dashboard 👍 
- The sketch provided has a good design and description is clear. My only comments here are that it would've been nice to include what information would be displayed in the tooltip and adding a title to your sketched dashboard as well as stating the data is from 2017
