### ISSUE TITLE
feedback in lab

### ISSUE THREAD

**Issue by Zhang-Haipeng** [UBC-MDS/DSCI_532_Group213_death_by_risk_factors#50]
Here are the suggestions discussed:
* Move the checkbox in the third plot to the top.
* Scale the numbers in the third plot (maybe use the percentage of death).
* Make it explicit that it's a global number for the first plot.
* Make the legend (scale) of the second plot constant among risk factors.

**Comment by mirohu** [comment]
Thanks Roc!
