### ISSUE TITLE
Peer Review from Jasmine & Dora

### ISSUE THREAD

**Issue by jasmineqyj** [UBC-MDS/DSCI_532_Group213_death_by_risk_factors#51]
Overall the dashboard is clear and well-organized. A few points regarding how it could be improved: 
- The three graphs should be connected in some way
- There are only 5 risk factors presented on map and in the trend graph
- Font size of legend of the line graph is small
- Vertical line could be a better tooltip for the trend graph
- The selector of the continent trend graph is at the bottom and not obvious to see
- The overall instructions are a little bit too much, maybe put them into three tabs separately

**Comment by mirohu** [comment]
Thank you Jasmine and Dora!
