### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by fsywang** [UBC-MDS/DSCI_532_Group213_death_by_risk_factors#53]
maintenance - miro
1. docstring (pep8) 
2. adding comment lines in .py file for each chunk of code 
3.  delete the app file in the master 
4. rearrange the text on the top (titles) 
5. radio button on the top
6. deploy the app

milestone 3
- update team contract: dividing the task (everyone has to review ) - florence
-  screenshot for new code/graph - florence
- update reflection - sakariya

check everything - florence 
make the link - miro

**Comment by mirohu** [comment]
maintenance - miro

DONE docstring (pep8)
DONE adding comment lines in .py file for each chunk of code
DONE delete the app file in the master
DONE rearrange the text on the top (titles)
DONE radio button on the top
DONE changing titles 
deploy the app

-----can you guys check the app.py file and the dashboard now to see if it's good to be deployed?------

milestone 3

update team contract: dividing the task (everyone has to review ) - florence
screenshot for new code/graph - florence
update reflection - sakariya
check everything - florence
make the link - miro
