### ISSUE TITLE
First draft of dashboard

### ISSUE THREAD

**Issue by fsywang** [UBC-MDS/DSCI_532_Group213_death_by_risk_factors#8]
![first_graph](https://user-images.githubusercontent.com/35549914/69390092-f42b9480-0c82-11ea-8807-2374ab61c7ad.jpg)

![second_graph](https://user-images.githubusercontent.com/35549914/69390104-01e11a00-0c83-11ea-8d41-00576b8db882.jpg)

![third_graph](https://user-images.githubusercontent.com/35549914/69390107-073e6480-0c83-11ea-8d42-e103bc4d1370.jpg)

**Comment by eyrakas** [comment]
We will convert these to the final design for the app.
